name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          cache: 'npm'
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm test

      - name: Generate SBOM
        run: npm sbom --sbom-format cyclonedx --omit dev > sbom.cyclonedx.json

      - name: Create GitHub Release
        run: gh release create ${{ github.ref_name }} sbom.cyclonedx.json --generate-notes --title ${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm publish --provenance --access public
